chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
Please review my code, thanks. You can find more info in:  #9
=> fixed: unbind moduleEventWatcher when deleting jvm plugin

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/exception/ExperimentException.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/handler/PreCreateInjectionModelHandler.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/handler/PreDestroyInjectionModelHandler.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/MethodPreInjectHandler.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/DestroyHandler.java
In chaos-exec-service module,When create or destory injection,currently has special  logic for the jvm plugin,but  the module is common,so can't include any special logics for one plugin.
So we need to avoid this and supply interfaces for plugin to extend. 
+ PreCreateInjectionModelHandler 
Model Level Handler before create injections
+ PreDestroyInjectionModelHandler 
Model Level Handler before destroy injections
=> refactor  model process flow when create or destroy injections

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/EnhancerModel.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/clazz/SuperClassMatcher.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/FrameworkModelSpec.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/DirectlyInjectionAction.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/connpool/AbstractConnPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/connpool/ConnectionPoolFullActionSpec.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/connpool/ConnectionPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/connpool/NoopConnectionPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/AbstractThreadPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/DefaultThreadPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/InterruptableRunnable.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/NamedThreadFactory.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/ThreadPoolFullActionSpec.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/ThreadPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/WaitingTriggerThreadPoolFullExecutor.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/handler/PreCreateInjectionModelHandler.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/handler/PreDestroyInjectionModelHandler.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ThreadUtil.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/DubboModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/DubboThreadPoolFullExecutor.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/provider/DubboProviderPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/oom/JvmOomActionSpec.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java
Add dubbo thread pool full chaos experiment for dubbo provider service.
Feature #22 
Get the `ExecutorService` of the `WrappedChannelHandler` class by reflection and submit runnable task.
Execute `blade create dubbo threadpoolfull` command for the dubbo provider service and the service returns the following error:
```
com.alibaba.dubbo.remoting.ExecutionException: class com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler error when process caught event .
at com.alibaba.dubbo.remoting.transport.dispatcher.all.AllChannelHandler.caught(AllChannelHandler.java:67)
at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandlerDelegate.java:44)
at com.alibaba.dubbo.remoting.transport.AbstractChannelHandlerDelegate.caught(AbstractChannelHandl …
```
=> feature: add dubbo thread pool full experiment

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/InterruptableRunnable.java
A numeric overflow bug as described in the issue #28 
the value of this expression actually is 889032704.
Now the expression value is 5184000000
=> fixed: Numeric overflow in expression

chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/cpu/CpuCountFlagSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/cpu/JvmCpuFullLoadActionSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/cpu/JvmCpuFullLoadExecutor.java
Feat #40 
Through the infinite loop to achieve CPU full load.
`--cpu-count` flag is cpu core number about full load, default is all cores.
Usage(You must execute prepare command first for jvm experiments):
`blade create jvm cfl`
`blade create jvm cpufullload`
`blade create jvm cfl --cpu-count 4`
=> feat: add cpu full load for jvm

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/DefaultStatusManager.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/StatusManager.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/StatusMetric.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/constant/ModelConstant.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/injection/Injector.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/BaseModelSpec.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/matcher/EffectCountMatcherSpec.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/matcher/EffectPercentMatcherSpec.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/StatusHandler.java
Limit the count of affected requests to control the impact.
Feature #46 
1. Add `effect-count` and `effect-percent` matcher flags in all actions(exclude cpu full load and oom).
2. Add a check before the action is executed.
1. Verify the `effect-count` flag by comparing the number of triggers with the returned hit result(see https://github.com/chaosblade-io/chaosblade/issues/100).
2. Verify the `effect-percent` flag by comparing the error rate with the flag value through a stress test with throw exception experiment.
=> feature: add limits of request count and percent in effect

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/prepare/AgentPrepareSpec.java
Because the chaosblade toolkit has add the `javaHome` flag in prepare jvm command, so add the flag to the project for adapt it.
See #52
=> feature: add javaHome flag to prepare spec

chaosblade-exec-common/src/tests/java/com/alibaba/chaosblade/exec/common/util/SQLParserUtilTest.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/test/java/com/alibaba/chaosblade/exec/plugin/jvm/Base64UtilTest.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/test/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaUtilsTest.java
I've analysed your codebase and noticed that `com.alibaba.chaosblade.exec.plugin.jvm.script.java.JavaUtils`, `com.alibaba.chaosblade.exec.plugin.jvm.Base64Util` and `com.alibaba.chaosblade.exec.common.util.SQLParserUtil`  is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
=> Add unit tests for JavaUtils, Base64Util and SQLParserUtil

chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletRequestPathMatcherSpec.java
1.chaosblade-exec-plugin-servlet adds requestpath flag
The values of servletpath and pathinfo are affected by the web.xml configuration. It is not easy to get the correct value when using it. Added requestpath flag, which is equivalent to requesturi without contextpath.
https://github.com/chaosblade-io/chaosblade/issues/134
join servletpath and pathinfo
=> servlet plugin: add requestpath flag

chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/codecache/CodeCacheFillingActionSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/codecache/CodeCacheFillingExecutor.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/codecache/DynamicJavaClassGenerator.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaUtils.java
Code cache is memory area for store code of JNI or jit compiled. Jit compiler will be disabled when code cache is full. Code cache full is a scenario which make system running slow down.
How to use:
> blade p jvm --process xxx
> blade create jvm CodeCacheFilling
=> Add support for jvm code cache full

Makefile, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ActionSpecBean.java
Signed-off-by: xcaspar <x.caspar@gmail.com>
chaosblade-io/chaosblade#410
Add `programs` field with `java` value in model spec.
=> feature:add programs field in model spec

chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaCodeScriptEngine.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/ClassLoaderForScript.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/DynamicScriptExecutor.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/JvmDynamicActionSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/ScriptExternalJarFlagSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/ScriptExternalJarPathFlagSpec.java
Describe what this PR does / why we need it
Does this pull request fix one issue?
https://github.com/chaosblade-io/chaosblade/issues/369
use URLClassLoader
````
blade c jvm script --debug --classname com.xy.basic.StringTest --methodname getString --external-jar file:/temp/hutool-all-5.2.5.jar --script-content xxx
````
````
blade c jvm script --debug --classname com.xy.basic.StringTest --methodname getString --external-jar https://repo1.maven.org/maven2/cn/hutool/hutool-alla/5.3.10/hutool-all-5.3.10.jar --script-content  xxx
````
````
blade c jvm script --debug --classname com.xy.basic.StringTest --methodname getString --external-jar-path /temp --script-content xxx
````
=> feature:script support load external jar

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/StringUtils.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbasePlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbasePointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseTableMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/pom.xml
支持Hbase中间件
org.apache.hadoop.hbase.TableName#valueOf在获取TableName方法进行切点，完成故障模拟
hbase指定表操作异常：./blade create hbase throwCustomException --table table_test --exception java.lang.Exception
hbase指定表操作延迟：./blade create hbase delay --table test_table --time 3
=> init hbase plugin

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/CustomMatcher.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/injection/Injector.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletParamsMatcher.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletQueryStringRegexPatternMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletRequestPathRegexPatternMatcherSpec.java
add regex pattern parameter for servlet to minimize blast radius
Fixes #176 
./blade create servlet modifyCode --code 500 --requestpath-regex-pattern /greeting/2* -d
./blade create servlet modifyCode --code 500 --querystring-regex-pattern name=1* -d
=> add regex pattern parameter for servlet to minimize blast radius

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/clazz/AndClassMatcher.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/injection/Injector.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/LogConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/LogPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/logback/LogbackEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/logback/LogbackPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/logback/LogbackPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/model/LogModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/model/LogbackModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/pom.xml
支持日志框架的故障演练，例如delay、throw exception：
```
blade create log delay --logback --time 1000 --effect-count 100
blade create log throwCustomException --logback --exception java.lang.NullPointException
```
Fixes #179
=> Support chaos experiments for log framework

chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/CallPointMatcher.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/CallPointMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/DubboModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/CallPointMatcher.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/CallPointMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/HttpModelSpec.java
- **Support Dubbo/HTTP call point match.**
```
blade create http delay --time 500 --uri http://api.bservice.xxx.com/api/user/list --call-point com.xxx.service.AService|a1Method
```
When the request is sent from **AService.a1method**, the delay executor takes effect. When the request is sent from **AService.a2method**, the delay executor will not be triggered.
- **Fix Dubbo consumer generalization invoke methodname bug.**
```
dubbo matchers: {"matchers":{"appname":"test_provider","service":"com.test.provider.api.DubboTestService","version":"1.0.0","group":"test","methodname":"testDubbo","timeout":"3000"}}
```
The generalization call of Dubbo consumer is right in identifying the method name. 
Fixes #185 #186
=> Support Dubbo/HTTP call point match and fix Dubbo generalization invoke methodname bug

Makefile, chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml, chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java, chaosblade-exec-bootstrap/pom.xml, chaosblade-exec-common/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-druid/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-elasticsearch/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-http/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-kafka/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-rabbitmq/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-tars/pom.xml, chaosblade-exec-plugin/pom.xml, chaosblade-exec-service/pom.xml, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ActionSpecBean.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/RefreshFlagBean.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/ModelParser.java, pom.xml
If you use `create` command to execute java experiments, the java agent will be loaded by default, but you can't reload it when the java agent update. So provide the `refresh` flag to reload it.
chaosblade-io/chaosblade#524
1. Add `refresh` flag in java experiment.
2. Add the `refresh` judgement in blade command.
Re-execute `blade c jvm cpufullload --process tomcat --cpu-count 1` without `refresh` command, the chaosblade log is as follows:
Re-execute `blade c jvm cpufullload --process tomcat --cpu-count 1 --refresh`, the chaosblade log is as follows:
=> Support refresh flag for reloading the java agent

chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ActionSpecBean.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/JavaHomeFlagBean.java, chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/ModelParser.java
Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
Specify the JAVA_HOME address through this parameter for loading the chaosblade java agent.
1. Add `javaHome` flag.
2. Parse the flag in chaosblade cli.
Compile and test it.
```
blade c jvm cpufullload --javaHome /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home --process tomcat --refresh 
```
=> feature: add javaHome flag in creating operation

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/context/GlobalContext.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/context/HashedWheelTimer.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/context/ThreadLocalContext.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/context/Timeout.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/context/Timer.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/context/TimerTask.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ClassUtils.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/FlagUtil.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientEnhancerWrapper.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientHandlerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/HttpProtocolEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/NettyRequestSenderEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/enhancer/InternalEnhancerContainer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/enhancer/InternalPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/resttemplate/RestTemplateEnhancer.java
- fix async http client call-point feature
- fix RestTemplate timeout config
- call-point performance optimization
=> fix async http client call-point feature and rest timeout

chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/provider/DubboProviderEnhancer.java
Fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/215
=> dubbo provider add getBusinessParams

chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/src/main/java/com/alibaba/chaosblade/exec/plugin/jedis/Jedis3orLessEnhancerStrategy.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/src/main/java/com/alibaba/chaosblade/exec/plugin/jedis/Jedis4EnhancerStrategy.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/src/main/java/com/alibaba/chaosblade/exec/plugin/jedis/JedisEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/src/main/java/com/alibaba/chaosblade/exec/plugin/jedis/JedisMultiVersionStrategy.java
Added support for the jedis 4.0 version of the jedis plugin
Signed-off-by: liuhq <15669072513@163.com>
Added support for the jedis 4.0 version of the jedis plugin
Fixes #225 
By being compatible with the latest jedis 4.0 main class method :
redis.clients.jedis.Protocol.sendCommand 
By packaging exec-jvm and then verifying it on the Linux machine, the chaosblade command can be executed correctly
=> feat(small):Added jedis plugin multi-version support

chaosblade-exec-plugin/chaosblade-exec-plugin-feign/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/FeignConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/FeignPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/FeignProducerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/FeignProducerPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/model/FeignModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/model/ServiceNameMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/model/UrlMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/test/java/com/alibaba/chaosblade/exec/plugin/feign/FeignProducerEnhancerTest.java, chaosblade-exec-plugin/pom.xml
hi , i develop fegin plugin, want merge to community repo。
i have completed the self-test in the company environment。
Describe how to verify it
this plugin test in spring-cloud-starter-openfeign [3.1.1,2.1.1.RELEASE];
the test points are delay and throwCustomException, which have been verified correctly.
please review code and merge it;
thanks
=> feature: add spring cloud feign plugin

chaosblade-exec-plugin/chaosblade-exec-plugin-elasticsearch/src/main/java/com/alibaba/chaosblade/exec/plugin/elasticsearch/index/AbstractRequestIndex.java, chaosblade-exec-plugin/chaosblade-exec-plugin-elasticsearch/src/main/java/com/alibaba/chaosblade/exec/plugin/elasticsearch/index/impl/SearchRequestIndex.java
org.elasticsearch.action.search.SearchRequest.indices  returns an array instead of a string。
This bug leads to the error "java.lang.classcastexception: [ljava.lang.string; cannot be cast to Java. Lang.string" when requesting searchrequest, although the test injection is successful
Es source code in "https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/search/SearchRequest.java#L558"
=> fix: SearchRequest.indices return error

chaosblade-exec-plugin/chaosblade-exec-plugin-clickhouse/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-clickhouse/src/main/java/com/alibaba/chaosblade/exec/plugin/clickhouse/ClickhousePlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-clickhouse/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/java/com/alibaba/chaosblade/exec/plugin/zookeeper/ZookeeperConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/java/com/alibaba/chaosblade/exec/plugin/zookeeper/ZookeeperEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/java/com/alibaba/chaosblade/exec/plugin/zookeeper/ZookeeperModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/java/com/alibaba/chaosblade/exec/plugin/zookeeper/ZookeeperPathMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/java/com/alibaba/chaosblade/exec/plugin/zookeeper/ZookeeperPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/java/com/alibaba/chaosblade/exec/plugin/zookeeper/ZookeeperPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-zookeeper/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/pom.xml
Signed-off-by: 15669072513 <15669072513@163.com>
add feature :add plugin zookeeper and clickhouse
Fixes #235
=> add feature :add plugin zookeeper and clickhouse

chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/gc/FullGCExecutor.java
When we inject a jvm full-gc fault, it is always failed first time.
After I has optimized the return info with execption stack trace, I found it was a java.lang.IllegalArgumentException from ScheduledThreadPoolExecutor.scheduleAtFixedRate because of the interval equal 0.
So, I fixed it by check interval, and use default and minimal value is 1.
Signed-off-by: NigelWu95 <bingheng.wbh@antgroup.com>
=> fix: create injection failed:null

chaosblade-exec-plugin/chaosblade-exec-plugin-security/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/java/com/alibaba/chaosblade/exec/plugin/security/SecurityConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/java/com/alibaba/chaosblade/exec/plugin/security/SecurityEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/java/com/alibaba/chaosblade/exec/plugin/security/SecurityMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/java/com/alibaba/chaosblade/exec/plugin/security/SecurityModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/java/com/alibaba/chaosblade/exec/plugin/security/SecurityPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/java/com/alibaba/chaosblade/exec/plugin/security/SecurityPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-security/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/pom.xml
一个 SpringSecurity 的故障注入插件
如果使用 SpringSecurity 框架，可以对用户登录流程进行故障注入
NONE
内部对 UserDetailsService$loadUserByUsername(String username) 方法做切面，可对指定用户进行延迟登录或抛异常等操作
如果对 AuthenticationManager$authenticate(Authentication authentication) 做切面会多次触发
创建 SpringBoot 项目，使用 SpringSecurity 框架，进行认证流程配置（按框架默认配置或自定义配置）
注入后用指定用户登录，可看到延迟或异常
NONE
=> spring security plugin

chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/injection/Injector.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/Model.java, chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/ActionModel.java
fix:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/259
=> update model tostring

chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaCodeScriptEngine.java
I fixed a bug, please see the issue #299 
please see the issue #299 
I added a new way of logging so that the program can display the real error on the production environment.
I was able to reproduce the error locally using the following code
```java
public static void main(String[] args) {
String content = "package com.taobao.csp.monkeyking.script.java.source;\n" +
"import java.util.Map;\n" +
"public class CornApplication {\n" +
"    public Object run(Map<String, Object> params) {\n" +
"        return \"agents\";" +
"}\n" +
"}";
Script script = new Script("1", null, null, content, null);
JavaCodeScriptEngine engine = new JavaCodeScriptEngine();
Object compile = engine.compile(script, CompileFailedTest.class.getClassLoader(), null);
}
=> fix: unable to access java.lang in JDK 11 version

chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseColumnMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbaseModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/src/main/java/com/alibaba/chaosblade/exec/plugin/hbase/HbasePointCut.java
A new feature for HBASE chaos experiments is introduced in this PR. For now hbase has been supported by ChaosBlade, this new feature would help to expand the boundary of tool ability to further more.
fixes #323 
Currently, chaosblade supports fault injection for tables using delay and throwCustomException methods, and on this basis, it expands to support fault injection for columns using delay and throwCustomException methods.
```
blade create hbase delay --column coloumn1 --time 1000  --pid 12345
blade create hbase throwCustomException --exception  java.lang.Exception --column column2 --pid 12345
```
=> feat: a new feature for HBASE components

chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/pom.xml, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/common/HdfsConstant.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/common/HdfsModelSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/common/HdfsPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/common/flag/HdfsFileMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/flag/HdfsRestfulOperationMatcherSpec.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/httpfs/HdfsHttpFSEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/httpfs/HdfsHttpFSPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/httpfs/HdfsHttpFSPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/webhdfs/HdfsWebHdfsEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/webhdfs/HdfsWebHdfsPlugin.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/java/com/alibaba/chaosblade/exec/plugin/hdfs/restful/webhdfs/HdfsWebHdfsPointCut.java, chaosblade-exec-plugin/chaosblade-exec-plugin-hdfs/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin, chaosblade-exec-plugin/pom.xml
A new plugin for HDFS chaos experiments is introduced in this PR. For now some big data components (hbase, kafka, elasticsearch, zookeeper, etc.) have been supported by ChaosBlade, this new plugin would help to expand the boundary of tool ability to further more.
Fixes #319.
The HDFS plugin is compatible with ChaosBlade JVM plugin architecture, which provides two basic experimental actions, delay and throwCustomException by default. In this initial versoin, the plugin focuses on simulating above faults when users try to access HDFS files via restful service. Although there are two different types of implementation in HDFS rest service which sharing the same API, the plugin can automatically adapt itself to inject corresponding faults to the target HDFS process.
In addition to default …
=> feat: new plugin for HDFS experiments

chaosblade-exec-plugin/chaosblade-exec-plugin-kafka/src/main/java/com/alibaba/chaosblade/exec/plugin/kafka/consumer/KafkaConsumerEnhancer.java, chaosblade-exec-plugin/chaosblade-exec-plugin-kafka/src/main/java/com/alibaba/chaosblade/exec/plugin/kafka/model/ConsumerTopicMatcher.java
1. The Kafka consumer experiment is compatible with all client versions; 
2. When the consumer subscribes to multiple topics, it can correctly inject faults through the topic parameter;
fixes #339 
i read maybe all version of KafkaConsumer, and found maybe 4 version.
for groupId:
1. [0-2.5), groupId = KafkaConsumer.groupId, type = string;
2. [2.5-3.7)  groupId = KafkaConsumer.groupId, type = Optional<string>;
3. [3.7,+)  KafkaConsumer.delegate = ClassicKafkaConsumer/LegacyKafkaConsumer
groupId = ClassicKafkaConsumer/LegacyKafkaConsumer.groupId;
4. [3.7,+) KafkaConsumer.delegate = AsyncKafkaConsumer
groupId = AsyncKafkaConsumer.groupMetadata.groupId;
for topic:
1. [0, 3.7) topics = KafkaConsumer.metadata.topics/subscription
2. [3.7, +) topics = KafkaConsumer.deletgate.metadata.subscription …
=> fix: Kafka consumer experiment is not effective
