chaosblade-io/chaosblade-exec-jvm

- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java
the if statement is wrong when action spec is null
> fix:fix bug when actionSpec is null

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/DefaultThrowExceptionExecutor.java
> fix: throw self-defined exception occur error #8

- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-bootstrap/pom.xml
- chaosblade-exec-common/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/pom.xml
- chaosblade-exec-plugin/pom.xml
- chaosblade-exec-service/pom.xml
- pom.xml
> chore: update version to 0.0.3

- chaosblade-exec-common/src/tests/java/com/alibaba/chaosblade/exec/common/util/StringUtilsTest.java
I've analysed your codebase and noticed that `com.alibaba.chaosblade.exec.common.util.StringUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.
> Add unit tests for com.alibaba.chaosblade.exec.common.util.StringUtils

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/matcher/BasePredicateMatcherSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/ClassNameMatcherSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodModelSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodNameMatcherSpec.java
> feat: Set classname and method  required when jvm fault injection

- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/BeforeEventListener.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ReflectUtil.java
Bugfix
Fixes [chaosblade #83](https://github.com/chaosblade-io/chaosblade/issues/83)
Add a new `getMethod` that returns method by descriptor in `ReflectUtil` class.
> bugfix: fix method not found for jvm experiment

- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/DubboModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/GroupMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/test/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboEnhancerTest.java
- pom.xml
Fixes #49: Dubbo interceptor should support group 
split dubbo service into `group`,`service` and `version`
> Fixes #49: Dubbo interceptor should support group 

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/injection/Injector.java
I found some hard code when I read this repo, so I fix it.
No, just a optimization.
> Replace hard code to ModelContant.

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/DefaultThrowExceptionExecutor.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/ExceptionMessageFlagSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/ThrowCustomExceptionActionSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/ThrowExceptionExecutor.java
Specify the exception message to simulate realistic exception.
add exception message flag
blade create jvm throwCustomException --exception java.lang.Exception --exception-message "I am exception message" --classname xxx --methodname xxx
> feature: add exception-message flag

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/prepare/AgentPrepareSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ModelUtil.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ActionSpecBean.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ProcessIdBean.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/ModelParser.java
See https://github.com/chaosblade-io/chaosblade/issues/132 for the detail.
Add pid flag in preparation.
```
blade prepare jvm --pid 2718
blade create jvm tce --exception java.lang.Exception --classname com.example.controller.DubboController --methodname hello --effect-percent 100 --pid 2718
```
Fix the wether experiment exists bug.
> feature: add --pid for preparation

- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java
> 修复重复注册jvmScript的bug

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ReflectUtil.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlDatabaseMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlHostMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlPortMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlSqlTypeMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlTableMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
with command
blade create psql delay  --process xxxx --time 2000 --table yyy --sqltype select
> feature: add support for postgrelsql

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/BeforeEnhancer.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/connpool/WaitingTriggerConnectionPoolFullExecutor.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/WaitingTriggerThreadPoolFullExecutor.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/LogUtil.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/src/main/java/com/alibaba/chaosblade/exec/plugin/druid/DruidDataSourceEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient4/HttpClient4Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/oom/executor/JvmOomExecutor.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rocketmq/RocketMqEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletEnhancer.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java
#75 
add `--debug` flag when execute create command
```
blade c dubbo delay --service com.example.service.DemoService --time 3000 --consumer --debug
```
> feature: add support for debug mode

- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/AfterEventListener.java
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/BeforeEventBean.java
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxEnhancerFactory.java
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/AfterEnhancer.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/BeforeEnhancer.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/Enhancer.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/PluginBean.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodAfterMatcherSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodConstant.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodEnhancer.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodEnhancerForAfter.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodEnhancerForBefore.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodModelSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodPlugin.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/PluginUtil.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/MethodPreInjectHandler.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/DynamicScriptExecutor.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/JvmDynamicActionSpec.java
#91 
Add after event handler.
Modify the true return object of the specify method.
command:
`./blade c jvm script --classname com.example.controller.DubboController --methodname getBean --script-file xxx/src/main/java/com/example/controller/ReturnScript.java --script-name test_return --after`
```java
public class ReturnScript {
public Object run(Map<String, Object> params) {
com.example.controller.TestBean bean = (com.example.controller.TestBean)params.get("return");
ArrayList<String> animal = new ArrayList<String>();
animal.add("cat");
animal.add("dog");
bean.setAnimal(animal);
return bean;
}
}
```
Get the true return object by `params.get("return")` and modify it.
> feature: support after event processing of method

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ReflectUtil.java
#96 fix unable to find non-public method of super class
> fix unable to find non-public method of super class

- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/DynamicScriptExecutor.java
Sometimes need to get the information of the target object when using jvm script command.
#94 
add `target` key in params object
> feature: support targe object in params

- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-bootstrap/pom.xml
- chaosblade-exec-common/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/DubboEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/provider/DubboProviderEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/provider/DubboProviderPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/pom.xml
- chaosblade-exec-plugin/pom.xml
- chaosblade-exec-service/pom.xml
- pom.xml
> feat: add support for dubbo 2.7

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/DefaultStatusManager.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/StatusManager.java
- chaosblade-exec-service/pom.xml
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/SpecMain.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/DestroyHandler.java
See chaosblade-io/chaosblade#239 for details.
Keep the original way of destroying with uid and add a new destroying way which through target and action parameters.
Create multiple experiments to verify with `destroy uid` and `destroy <TARGET> <ACTION>` commands, for examples:
```
blade create jvm delay --time 3000 --classname xxx --methodname xxx
blade create jvm delay --time 3000 --classname yyy --methodname yyy
blade create jvm tce --exception java.lang.Exeception --classname zzz --methodname zzz
```
then destroy them using the flowing commands:
```
blade destroy jvm delay
blade destroy 4e7eb25fddd77a39
```
> feature: enhance destroy command

- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/ModelParser.java
fix the jvm agent bug: use uid as a parameter
Fixes #105 
modify ModelParser.java line 38, assistantFlag add uid
> fix jvm use uid as a parameter

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/DefaultThrowExceptionExecutor.java
fix the jvm agent bug: Execute jvm throwDeclaredException experiment throws java.lang.NullPointerException
Fixes #104
Check whether exceptionMessageFlag is null first
> bugfix: fix execute jvm throwDeclaredException experiment throws NullPointerException

- chaosblade-exec-common/pom.xml
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/BaseReturnValueExecutor.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/Calculator.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/CompilerException.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/Constant.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/ConstantType.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/Lexicon.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/Syntactic.java
- chaosblade-exec-common/src/tests/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/SyntacticTest.java
由于业务的异常情况需要在原始返回值的基础上进行加工生成新的返回值
函数名称 | 意义
-- | --
min(arg1, arg2, …) | 参数中最小值，参数个数大于1（字符串和数字）
max(arg1, arg2, …) | 参数中最大值，参数个数大于1（字符串和数字）
sum(arg1, arg2, …) | 参数只和（数字）
avg(arg1, arg2, …) | 参数均值（数字）
count(arg1, arg2, …) | 参数均值
random() | 值在[0,1)区间内且密度函数为均匀分布的随机数
numeric() | 转化为数字
string() | 转化为字符串
boolean() | 转化为boolean
if(arg1,arg2,arg3) | 如果arg1为真，返回arg2，否则arg3
sin(arg1) | 弧度制的sin函数值（数字）
cos(arg1) | 弧度制的cos函数值（数字）
asin(arg1) | 弧度制的asin函数值（数字）
acos(arg1) | 弧度制的acos函数值（数字）
|运算符 | 意义|
|-- | --|
|= | 判断相等，返回boolean|
|> | 判断大于，返回boolean|
|< | 判断小于，返回boolean|
|>= | 判断大于等于，返回boolean|
|<= | 判断小于等于，返回boolean|
|+ | 加法操作|
|- | 减法操作|
|* | 乘法操作|
|/ | 除法操作|
|^ | 指数操作|
|% | 取模操作|
|or | 或运算，返回boolean|
|and | 与运算，返回boolean|
|() | 左右括号|
变量 | 意义
-- | --
r | 原始函数返回值，需要增加—after参数否则无效
p0 | 函数第一个参数
p1 | …
> 增强 jvm return 功能，增加返回值的函数和运算符计算

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/DefaultThrowExceptionExecutor.java
bugfix throwCustomExecption --exception-message no take effect
fixed #115  
Cache the default constructor, find the simple-string-param constructor.
Signed-off-by: Qibin Yu <422274064@qq.com>
> bugfix throwCustomExecption --exception-message no take effect

- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rocketmq/RocketMqConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rocketmq/RocketMqEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rocketmq/RocketMqPointCut.java
try to support apache rocketmq
Fixes #120 
Special processing prefix "org.apache"
> feature: support apache rocketmq

- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/consumer/DubboConsumerEnhancer.java
fix a bug
Fixes the Issue #122 
correct the word
> fix-bug,the static classname error

- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/TarsConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/TarsEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/TarsPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/client/TarsClientEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/client/TarsClientPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/client/TarsClientPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/model/ClientMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/model/FunctionNameMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/model/ServantMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/model/ServantNameMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/model/TarsModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
- chaosblade-exec-plugin/pom.xml
try to support the tars component to inject the error(timeout、 custom exception)
Fixes #124
add a plugin tars， use the same structure like dubbo，then cut in the place where that "invoke"
the test demo in
testClient https://github.com/saikei/tarsclient
testServer https://github.com/saikei/tarsserver
> support tars component

- CONTRIBUTING.md
Improvement of grammer on the CONTRIBUTING.md file
> improvement on the CONTRIBUTING.md file

- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/UrlUtils.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient3/HttpClient3Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient3/HttpClient3PointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient4/HttpClient4Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient4/HttpClient4Plugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient4/HttpClient4PointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/HttpModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/Okhttp3MatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/okhttp3/Okhttp3Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/okhttp3/Okhttp3Plugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/okhttp3/Okhttp3PointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/resttemplate/RestTemplateEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
add Okhttp3 Enhancer
Fixes #128 
pointcut
- class matcher : okhttp3.RealCall
- method matcher : execute
1. dependency 
```
<dependency>
<groupId>com.squareup.okhttp3</groupId>
<artifactId>okhttp</artifactId>
<version>3.4.1</version>
</dependency>
```
2. execute a get reuqest demo (kotlin demo)
```
val request = Request.Builder()
.url(url)
.build()
val client = OkHttpClient.Builder().build()
try {
val response = client.newCall(request).execute()
log.info("http code : {}, msg : {}", response.code(), String(response.body().bytes(), StandardCharsets.UTF_8))
} catch (e: Exception) {
log.error(e.message, e)
}
```
3. start the demo , and blade process 
```
./blade create http delay --okhttp3 --uri http://i.cvte.com/ --time 3000 --timeout 3000 …
```
> ⚡ add Okhttp3 Enhancer

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/ModelSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/ActionSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/BaseActionSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/delay/DelayActionSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/exception/ThrowCustomExceptionActionSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/ThreadPoolFullActionSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/plugin/MethodModelSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ReflectUtil.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/src/main/java/com/alibaba/chaosblade/exec/plugin/druid/DruidModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/DubboModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/HttpModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/src/main/java/com/alibaba/chaosblade/exec/plugin/jedis/JedisModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/codecache/CodeCacheFillingActionSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/cpu/JvmCpuFullLoadActionSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/oom/JvmOomActionSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/oom/flag/JvmMemoryAreaFlagSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/model/JvmDynamicActionSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/src/main/java/com/alibaba/chaosblade/exec/plugin/postgrelsql/PostgrelsqlModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-rabbitmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rabbitmq/model/RabbitMqModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rocketmq/RocketMqModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/TarsEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/src/main/java/com/alibaba/chaosblade/exec/plugin/tars/model/TarsModelSpec.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ActionSpecBean.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ModelSpecBean.java
improvement the action use case
#chaosblade 401
`blade create http delay -h`
> feature:improvement the action use case

- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
https://github.com/chaosblade-io/chaosblade/issues/372
exclusion com.sun:tools:jar:1.8
make
> fixbug: Could not find artifact com.sun:tools:jar:1.8

- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaCodeScriptEngine.java
https://github.com/chaosblade-io/chaosblade/issues/386
#137
> finxbug: Compile script exception

- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBCollectionMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBDatabaseMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBSqlTypeMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
- chaosblade-exec-plugin/pom.xml
add support for mongodb.
./blade create mongodb delay --time 10000 --database ares --collection chaos -d 
./blade create mongodb throwCustomException --exception java.lang.Exception --database ares --collection chaos -d
> feature: add mongodb plugin.

- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/src/main/java/com/alibaba/chaosblade/exec/plugin/rocketmq/RocketMqModelSpec.java
improve mysql, rockerMq example console print
> improve mysql, rockerMq example console print

- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonCmdTypeMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonKeyMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/java/com/alibaba/chaosblade/exec/plugin/redisson/RedissonPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
- chaosblade-exec-plugin/pom.xml
support redisson
Fixes #152 
add the redisson executor point cut "org.redisson.command.CommandAsyncService"
> support redisson

- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/script/java/JavaCodeScriptEngine.java
> fix:修复编译java代码会导致内存泄露问题

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ReflectUtil.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceActionExecutor.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceCmdMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceConstants.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceKeyMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceModeSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettucePlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettucePointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/LettuceValueFlagSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/java/com/alibaba/chaosblade/exec/plugin/lettuce/UpdateActionSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/Mysql5Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/Mysql8Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlPointCut.java
- chaosblade-exec-plugin/pom.xml
#150 
````
blade create mysql delay --time 2000 --sqltype select --port 10038 --process SelectTest
````
````
blade create lettuce delay --key name --time 2000
blade create lettuce throwCustomException --exception java.lang.Exception --key name
blade create lettuce update --value "i'm hacker" --key name --process Lettuce
````
> Added Lettuce client & MySQL Driver 8.x support

- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/code/HttpCodeFlagSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/code/ModifyHttpCodeActionExecutor.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/code/ModifyHttpCodeActionSpec.java
feature: Servlet return custom status code(4xx,5xx)
#129 
Servlet return custom status code(4xx,5xx)
````
blade c servlet mc --requestpath /topic --code=404 --process Sme
````
request  /topic
> feature: Servlet return custom status code(4xx,5xx)

- Makefile
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-bootstrap/pom.xml
- chaosblade-exec-common/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-elasticsearch/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-kafka/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rabbitmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/pom.xml
- chaosblade-exec-plugin/pom.xml
- chaosblade-exec-service/pom.xml
- pom.xml
> chore: update version to 1.2.0

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/clazz/InterfaceClassMatcher.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/AsyncHttpClientPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient3/HttpClient3Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient4/HttpClient4Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/AsyncHttpClientMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/HttpModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/okhttp3/Okhttp3Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/resttemplate/RestTemplateEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
- http故障模拟支持async-http-client. 
- 各类httpclient支持超时演练：async-http-client、httpclient3、httpclient4、okhttp3、resttemplate.
- 修复http plugin的EnhancerModel设置错误问题.
Fixes #173
> Support http timeout

- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/JvmModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/gc/FullGCActionSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/gc/FullGCEffectCountFlagSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/gc/FullGCExecutor.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/gc/FullGCIntervalFlagSpec.java
支持触发jvm fullGC故障演练：
```blade create  jvm full-gc --interval 1000 --effect-count 100```
Fixes #178
> Support jvm fullgc experiment

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/injection/Injector.java
change some log level  to debug in com.alibaba.chaosblade.exec.common.injection.Injector 
Because this place is executed very frequently, there are too many info logs
> refactor: change some log level to debug

- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/java/com/alibaba/chaosblade/exec/plugin/gateway/GatewayConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/java/com/alibaba/chaosblade/exec/plugin/gateway/GatewayEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/java/com/alibaba/chaosblade/exec/plugin/gateway/GatewayModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/java/com/alibaba/chaosblade/exec/plugin/gateway/GatewayPathMatcherSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/java/com/alibaba/chaosblade/exec/plugin/gateway/GatewayPlugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/java/com/alibaba/chaosblade/exec/plugin/gateway/GatewayPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
- chaosblade-exec-plugin/pom.xml
springCloud Gateway plugin add，fault injection of delays and exceptions can be implemented
> SpringCloud Gateway Plugin Add

- Makefile
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-bootstrap/pom.xml
- chaosblade-exec-common/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-elasticsearch/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-kafka/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rabbitmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/pom.xml
- chaosblade-exec-plugin/pom.xml
- chaosblade-exec-service/pom.xml
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/ActionSpecBean.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/JavaHomeFlagBean.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/build/RefreshFlagBean.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/ModelParser.java
- pom.xml
> Release v1.3.0 version

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/matcher/BusinessParamsMatcherSpec.java
Fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/214
> 1.4 check params

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/DefaultThreadPoolFullExecutor.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/ThreadPoolFullExecutor.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/threadpool/WaitingTriggerThreadPoolFullExecutor.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/src/main/java/com/alibaba/chaosblade/exec/plugin/dubbo/model/DubboThreadPoolFullExecutor.java
Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
chaosblade-io/chaosblade#627
Invoke `getExecutor` method when `getExecutorService` doesn't exist.
Package and test it.
> Fix dubbo thead pool doesn't take effect under some conditions

- pom.xml
Signed-off-by: wufan <wufunc@gmail.com>
fix #211
> fix compile error

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamMatcher.java
Signed-off-by: wufan <wufunc@gmail.com>
add debug log
> add  debug log

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamAndMatcher.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamMatcher.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamNotMatcher.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamOrMatcher.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamPatternEnum.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/matcher/busi/BusinessParamPatternMatcher.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/matcher/BusinessParamsMatcherSpec.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/BusinessParamUtil.java
add business param pattern match
fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/227
> add business param pattern match

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/DefaultReturnValueExecutor.java
support jvm return any type
Fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/223
> support jvm return any type

- Makefile
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-bootstrap/pom.xml
- chaosblade-exec-common/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-druid/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-dubbo/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-elasticsearch/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-gateway/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-hbase/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jedis/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-kafka/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-lettuce/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-postgrelsql/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rabbitmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-redisson/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-rocketmq/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-tars/pom.xml
- chaosblade-exec-plugin/pom.xml
- chaosblade-exec-service/pom.xml
- chaosblade-exec-spi/pom.xml
- pom.xml
> chore: update version to 1.6.0

- chaosblade-exec-spi/pom.xml
Signed-off-by: wufan <wufunc@gmail.com>
optimize chaosblade-exec-spi from sub module as isolated module
> optimize chaosblade-exec-spi from sub module as isolated module

- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/src/main/java/com/alibaba/chaosblade/exec/bootstrap/jvmsandbox/SandboxModule.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/PluginBean.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/aop/PluginBeans.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/DefaultPluginBeanManager.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/ManagerFactory.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/center/PluginBeanManager.java
- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/BusinessParamUtil.java
- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java
lazy load plugin,this prevents the CPU idle rate from decreasing as all plug-ins are loaded when the Agent is suspended
Fixes:https://github.com/chaosblade-io/chaosblade/issues/663
Do not load all plug-ins when hanging on agent, and load corresponding plug-ins according to target when creating
Before modify cpu idle:
After modify cpu idle:
before  cpu profile:
after cpu profile:
> lazy load plugin

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/action/returnv/compiler/Syntactic.java
Signed-off-by: thinkergithub <tianmeng.gtm@alibaba-inc.com>
https://github.com/chaosblade-io/chaosblade/issues/743
fixed the return value with expr
Fixes chaosblade-io/chaosblade#743
> fix: mock value by expr

- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-servlet/src/main/java/com/alibaba/chaosblade/exec/plugin/servlet/ServletModelSpec.java
servlet support business params
fixes: https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/261
> servlet support business params

- Makefile
- chaosblade-exec-bootstrap/chaosblade-exec-bootstrap-jvmsandbox/pom.xml
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/src/main/java/com/alibaba/chaosblade/exec/plugin/jvm/gc/FullGCExecutor.java
depend sandbox 1.3.4 to support jdk18
> feature:depend sandbox 1.3.4 to support jdk18

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/model/matcher/SimplePredicateMatcherSpec.java
- chaosblade-exec-plugin/pom.xml
Signed-off-by: xcaspar <changjun.xcj@alibaba-inc.com>
> fix: Add missing files from clickhouse plugin

- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBPointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mongodb/src/main/java/com/alibaba/chaosblade/exec/plugin/mongodb/MongoDBSqlTypeMatcherSpec.java
Signed-off-by: arthur657834 <kingkom7834@126.com>
support mongo count method
add mongo count method
> optimize: support mongo count method

- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/LogConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/log4j2/Log4j2Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/log4j2/Log4j2Plugin.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/log4j2/Log4j2PointCut.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/model/Log4j2ModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/java/com/alibaba/chaosblade/exec/plugin/log/model/LogModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-log/src/main/resources/META-INF/services/com.alibaba.chaosblade.exec.common.aop.Plugin
Signed-off-by: xuji007 <xuji@njzfit.cn>
extension of log plugin enable it to support log4j2
> extension of log plugin enable it to support log4j2

- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/ApacheShardingJdbcEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/IoShardingJdbcEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-mysql/src/main/java/com/alibaba/chaosblade/exec/plugin/mysql/MysqlPointCut.java
The currently provided mysql plugin cannot support shardingjdbc, and special extension support.
no
Find the underlying classes and methods used by shardingjdbc, and perform delayed and abnormal faults.
The verification method is consistent with the original mysql plugin.
Only do extension support mysql plugin.
> Extend plugin-mysql to support shardingJdbc

- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/HttpConstant.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/asynchttpclient/HttpProtocolEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient3/HttpClient3Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/httpclient4/HttpClient4Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/model/HttpModelSpec.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/okhttp3/Okhttp3Enhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-http/src/main/java/com/alibaba/chaosblade/exec/plugin/http/resttemplate/RestTemplateEnhancer.java
- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml
fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/284
> fix http b-params

- chaosblade-exec-common/src/main/java/com/alibaba/chaosblade/exec/common/util/ConfigUtil.java
fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/289
> fix getActionFlag parseBoolean

- doc/zh-cn/design.md
> fixed:fix a typo from design.md 

- chaosblade-exec-service/src/main/java/com/alibaba/chaosblade/exec/service/handler/CreateHandler.java
https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/266
fixes:https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/266
> support load plugins based on consumer and provider

- chaosblade-exec-plugin/chaosblade-exec-plugin-jvm/dependency-reduced-pom.xml
- pom.xml
> fix: jackson-core version bump to 2.12.7

- chaosblade-exec-plugin/chaosblade-exec-plugin-feign/src/main/java/com/alibaba/chaosblade/exec/plugin/feign/FeignProducerEnhancer.java
Compatible with RequestTemplate in feign-core version 10.2.0 and above
Fixes #332  
```
./blade prepare jvm --pid 1
./blade create feign throwCustomException --exception java.lang.RuntimeException --exception-message mock-beans-exception --service-name test --url /testUrl --pid 1
```
> fix:compatible with RequestTemplate in feign-core version 10.2.0 and above
